// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(PersonsDbContext))]
    [Migration("20241215125441_inital")]
    partial class inital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Country", b =>
                {
                    b.Property<Guid>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CountryID");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            CountryID = new Guid("7cf40db8-7f7c-b531-f0a5-abf2d7cd778b"),
                            CountryName = "USA"
                        },
                        new
                        {
                            CountryID = new Guid("384b362a-0f7b-da3c-69bd-36e615484632"),
                            CountryName = "China"
                        });
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.Property<Guid>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("CountryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Gender")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("PersonName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("ReceiveNewsLetters")
                        .HasColumnType("bit");

                    b.HasKey("PersonID");

                    b.ToTable("Persons", (string)null);

                    b.HasData(
                        new
                        {
                            PersonID = new Guid("b7660feb-aa9b-4664-8190-f2b52e2681ad"),
                            Address = "4 Transport Center",
                            CountryID = new Guid("7cf40db8-7f7c-b531-f0a5-abf2d7cd778b"),
                            DateOfBirth = new DateTime(1985, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hbroad0@marketwatch.com",
                            Gender = "Male",
                            PersonName = "Harv",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("06b68984-41ee-4e3b-af4f-e57493198042"),
                            Address = "577 7th Terrace",
                            CountryID = new Guid("384b362a-0f7b-da3c-69bd-36e615484632"),
                            DateOfBirth = new DateTime(1993, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dlevensky1@barnesandnoble.com",
                            Gender = "Female",
                            PersonName = "Devan",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("621f8b35-8618-4c4f-b088-e961525a8e15"),
                            Address = "6 Parkside Hill",
                            CountryID = new Guid("7cf40db8-7f7c-b531-f0a5-abf2d7cd778b"),
                            DateOfBirth = new DateTime(2000, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tribbens2@blogger.com",
                            Gender = "Female",
                            PersonName = "Thomasin",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("6776db70-e3d6-49df-ba18-12dc86c968f2"),
                            Address = "80 4th Street",
                            CountryID = new Guid("384b362a-0f7b-da3c-69bd-36e615484632"),
                            DateOfBirth = new DateTime(1996, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tcampana3@hud.gov",
                            Gender = "Male",
                            PersonName = "Todd",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("e27ea869-7a6b-49d2-8a96-718ea4d8e8b0"),
                            Address = "1 Daystar Hill",
                            CountryID = new Guid("384b362a-0f7b-da3c-69bd-36e615484632"),
                            DateOfBirth = new DateTime(1991, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ahyatt4@bbb.org",
                            Gender = "Male",
                            PersonName = "Aloin",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("3aef3959-0c4e-4860-a66f-74c5d0563488"),
                            Address = "348 Anniversary Avenue",
                            CountryID = new Guid("384b362a-0f7b-da3c-69bd-36e615484632"),
                            DateOfBirth = new DateTime(1990, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fstrother5@vimeo.com",
                            Gender = "Male",
                            PersonName = "Frannie",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("304b8efd-f866-4566-a279-5b72f7f358c2"),
                            Address = "11866 Graceland Way",
                            CountryID = new Guid("384b362a-0f7b-da3c-69bd-36e615484632"),
                            DateOfBirth = new DateTime(1986, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dearsman6@cbsnews.com",
                            Gender = "Male",
                            PersonName = "Dilly",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("dfd67610-631e-4723-97fa-dbd92aab4526"),
                            Address = "68 Oakridge Crossing",
                            CountryID = new Guid("384b362a-0f7b-da3c-69bd-36e615484632"),
                            DateOfBirth = new DateTime(1983, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "amedlar7@umn.edu",
                            Gender = "Male",
                            PersonName = "Alphonso",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("aa0f0d65-2e9b-4b4f-91e9-9b93f5dc3280"),
                            Address = "40 Old Gate Junction",
                            CountryID = new Guid("384b362a-0f7b-da3c-69bd-36e615484632"),
                            DateOfBirth = new DateTime(1988, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bmersh8@aboutads.info",
                            Gender = "Female",
                            PersonName = "Bobby",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonID = new Guid("f26fda3f-a537-473f-8c6b-b47caff2cb86"),
                            Address = "161 Grasskamp Way",
                            CountryID = new Guid("384b362a-0f7b-da3c-69bd-36e615484632"),
                            DateOfBirth = new DateTime(1983, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jlearoid9@marketwatch.com",
                            Gender = "Female",
                            PersonName = "Jehanna",
                            ReceiveNewsLetters = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
